# Generated by Django 6.0.3 on 2026-03-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='creater',
            new_name='creator',
        ),
    ]
