# Generated by Django 6.0.3 on 2026-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_creater_form_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(related_name='questionss', to='index.questions'),
        ),
    ]
