# Generated by Django 6.0.3 on 2026-03-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_form_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='index.questions'),
        ),
    ]
