# Generated by Django 6.0.3 on 2026-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('viewer', 'Viewer'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
